### ISSUE TITLE
Books 7.1 

### ISSUE THREAD

**Issue by Brianmjr49** [ReverseApple/RemoveBooksDRM#8] opened 2024-11-05 07:00 UTC
Tried using this on the newest version (I believe it’s 7.1) and it didn’t actually remove the DRM. It was also having issues finding the files in the library. Of course that could also be the fact that I have no idea what I’m doing but I thought I’d bring it up.

**Comment by AngeloD2022** [comment] 2024-11-05 14:38
I am aware of this issue. The actual bypass still appears to work, but the problem is that Apple introduced some kind of sandboxing change that prevents the decrypted content from being written anywhere.

**Comment by AngeloD2022** [comment] 2024-11-07 14:43
This should be fixed with Version 2

**Closed as completed by AngeloD2022** 2024-11-07 14:43 UTC
